# ===============================
# APPLICATION
# ===============================
spring.application.name=gestion-immobilier

# ===============================
# DATABASE CONFIG (PostgreSQL)
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5433/gestion_immobilier_db
spring.datasource.username=immobilier
spring.datasource.password=Mhamed123
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ===============================
# CONNECTION POOL (HikariCP)
# ===============================
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.connection-timeout=20000

# ===============================
# SECURITY / KEYCLOAK
# ===============================
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8180/realms/gestion-immobilier
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8180/realms/gestion-immobilier/protocol/openid-connect/certs

# ===============================
# SERVER
# ===============================
server.port=8080
