# ===============================
# APPLICATION
# ===============================
spring.application.name=gestion-immobilier

# ===============================
# DATABASE CONFIG (PostgreSQL)
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5433/gestion_immobilier_db
spring.datasource.username=immobilier
spring.datasource.password=Mhamed123
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ===============================
# CONNECTION POOL (HikariCP)
# ===============================
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.connection-timeout=20000

# ===============================
# SECURITY / KEYCLOAK
# ===============================
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8180/realms/gestion-immobilier
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8180/realms/gestion-immobilier/protocol/openid-connect/certs

# ===============================
# KEYCLOAK ADMIN API (BIEN-34)
# ===============================
keycloak.admin.server-url=http://localhost:8180
keycloak.admin.realm=master
keycloak.admin.client-id=admin-cli
keycloak.admin.username=admin
keycloak.admin.password=Mhamed@1
keycloak.admin.realm-users=gestion-immobilier


# Actuator
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=when-authorized

# ===============================
# SERVER
# ===============================
server.port=8080

# ===============================
# UPLOAD (images biens immobiliers)
# ===============================
app.upload.dir=uploads
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=50MB

# ===============================
# CLOUDINARY
# ===============================
cloudinary.cloud-name=dh8tta9bj
cloudinary.api-key=112569293587456
cloudinary.api-secret=lVZkux-HLh2NhuTVnpemnly6GkY